### ISSUE TITLE
Spike: Data node connection

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#14]
Currently we use environment variables to set which data node an app should use for fetching data, but this poses some questions:
- What if that node goes down
- What if other viable data nodes are added to the pool
- What about apps that can't be hosted

It would be preferable to be able to connect (randomly or otherwise) to all the different data nodes in the network.

- Where and how can an app can fetch for a list of known data nodes or be compiled with a set of known nodes.
- How do we choose a node from that list? Should users be able to select a node of their choice?
- Should the connection to the selected node be persisted? What should happen if the user refreshes?
- Can this leverage IPFS?
- What if the chosen node is not suitable or runs older versions of the API

**Comment by gordsport** [comment]
@mattrussell36 - please can you update tasks / make a spike?

**Comment by campbellssource** [comment]
Here is how I imagine this working
<img width="1274" alt="Screenshot 2022-05-17 at 13 39 27" src="https://user-images.githubusercontent.com/13255539/168812798-207d33d8-0385-407f-be7e-f8c3da9c2949.png">
[Figma](https://www.figma.com/file/F995ESZ0QMpTBuQWGAgLRz/Vega-team-library?node-id=1386%3A67731)

If this design is correct (meeting to discuss on Fri 20 May) the tasks would be something like
- [ ] Spec this approach in detail
- [ ] Create tickets for data node
- [ ] Create a single source bootstrap network/nodes file in mono-repo (or better still have an external source maintained e.g. the wallet config)
- [ ] Refactor apps to share this single file (perhaps each app has a single env var to select a default network)
- [ ] Build cold app start logic (attempt to connect to nodes, get fresh list of nodes, randomly connect to one) 
- [ ] Build interface for user manually switching network/node
- [ ] Define the time outs to use for when the node stops responding and build appropriate UI
(but that's just like my opinion man)

**Comment by campbellssource** [comment]
We discussed this design and the actions. Here are some notes from discussion:

Where should the initial (static) list of known networks and nodes live? 
Proposal: networks repo could contain a file with the initial set of networks/nodes with action that posts changes into file used in the FE mono-repo. meaning that a build of an app contains the initial nodes list (IPFS hash contains this).  

Can we get a list of data nodes (with SSL Urls) registered on Vega so that clients can read Vega data?
any solution that we suggest today will be brittle until incentivised data node.
- there is no incentive for validators to do this now
- there is no way of ensuring they are doing this
- there may not be an SSL certificate in place
- the client may have to check the block height on that node is ~the same as others

Meaning that even if we build a feature in the UI that can select a node in a decentralised way, it will either fail in many cases, or will result in connecting to one of the few data nodes that do work. 

So options:
1) Just host some data nodes that the UIs ready from (with a feature that allows a user to enter their own or a host to overwrite)
2) Require incentive data node to be available before this UI feature is built  
3) Do a small iteration on what we have today but randomly selects from more than one data node
4) Build this UI feature now and accept the fact users may connect to dud node or we end up with the same limited number of nodes as today (but it will be more decentralised)

**Comment by gordsport** [comment]
closing as now superseded by: 
- https://github.com/vegaprotocol/frontend-monorepo/issues/464
