### ISSUE TITLE
Toast component

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#1677]
## The Chore

We need a design for a generic toast component added to the UI toolkit. This will initially be used for showing transaction statuses, but it should be flexible enough for other use cases too.

## Tasks

- [x] Brief/discuss use cases with UX/design team
- [x] Design
- [ ] Review
- [ ] Implement

## Additional details / background info

Note: Radix now has a toast component which we should probably leverage to ensure a11y and interaction concerns are covered. 

We may need both a Toast component and possibly a Toaster component to handle display of multiple toasts (probably stacking them as it will be possible to execute multiple tx simultaneously)

**Comment by PeteWilliams** [comment]
Worth pointing out that the Radix control automatically closes, and the docs say to use a Dialog styled as a Toast if you want it to stay open.
Generally I agree with the principle that we should only be using Toasts for things that don't require a user response, but I think the 'Confirm in wallet' notice might be an exception - it's should stay until dismissed or actioned in the wallet, but a toast rather than a modal would allow the user to continue using Console until they're ready to confirm the transaction.

**Comment by PeteWilliams** [comment]
Proposed design here: https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=3672%3A35294

Current thinking is that toasts would only be used to communicate things to the user something that the system has done - Not prompt them to do something.
So 'confirm in your wallet' would remain as dialogs.

### Proposed toast structure
![image](https://user-images.githubusercontent.com/1325606/196740739-3d333af6-e9af-4e7f-9ee0-5a0358b55be1.png)

### Behaviour

- Automatically closes after 4 seconds
- Fades away with 1500ms transition
- Doesn’t fade away while hovering, focussed or on window blur
- If already fading but then hover/focus on it, goes back to full opactity and stays until you move/focus away again
- Close via icon or swipe
- Multiples toasts should stack
- When above one fades out, ones below should move up

### Examples
![image](https://user-images.githubusercontent.com/1325606/196740971-36920711-6603-46b9-bd45-2f4bac375cc5.png)

### Position
![image](https://user-images.githubusercontent.com/1325606/196741106-d18051bd-4a77-4452-9b45-e70b3724ae87.png)

### Questions
What happens when you’re not there when event happens - ideally you'd get the notifications when you next log in, but I'd imagine that's a lot more work?
With fills you could potentially end up with dozens for a given order. Could the filled value stream until the toast goes?

**Comment by PeteWilliams** [comment]
I've done a quick mockup of how the transitions would ideally work: https://codepen.io/PeteWilliams/pen/mdKybbR

![toasts](https://user-images.githubusercontent.com/1325606/198060952-6ef235c3-7cc4-4c02-acaf-84c69a4b1622.gif)

Specification:
- Toasts appear in top right corner by fading in and sliding up 20px over 0.3s
- Should end in position 20px from top and right
- After 4 seconds, or when clicking close
   - toast slides out of screen and fades away over 0.75s
   - any toast(s) below slide up over 0.75s
 - If hovering/focussing on the toast, it doesn't fade away, nor do the ones below. Timer starts from 0 when hover away

**Comment by bigfandavid** [comment]
NICE! Will jump on this tomorrow - today has run away with me with swag stuff.

**Comment by bigfandavid** [comment]
Hi @mattrussell36 @PeteWilliams 

I did some research into UI design for toasts and then developed the UX work Pete has done (thanks!).

I've drawn up three initial options that I'd like to get feedback on... I'm drawn to the first option, but aware the third option is more aligned with other Vega UI elements.

Any thoughts? Happy to explore further if this hasn't hit the right note yet!

Cheers,
David

![Toasts_ Option 1](https://user-images.githubusercontent.com/113683891/198661724-7e76b4b1-bb38-479d-a4ca-d8675b6ee62c.jpg)
![Toasts_ Option 2](https://user-images.githubusercontent.com/113683891/198661737-6499dafd-50ac-4892-bdbf-de036a8528c6.jpg)
![Toasts_ Option 3](https://user-images.githubusercontent.com/113683891/198661745-afd7ce46-4589-4bdd-94e5-5837cdbea88d.jpg)

**Comment by PeteWilliams** [comment]
I like 1 and 3. Would be good to see them in situ to see how they'd look in Console. Probably best to stick to the existing  orange and red colours for warning and error. Blue could be a useful option for info though, maybe for things like notifications promoting new features or incentives in the future. The ones with a secondary line of content need more contrast for legibility though, and it'd be good to have the market name stand out a bit more.

**Comment by bigfandavid** [comment]
Thanks Pete - I've made some revisions and also placed both in situ for comparison. You can view the files here: https://www.figma.com/file/deV7EBxvTF4ggdsKVVosfr/Console-V2?node-id=631%3A4624

Let me know your thoughts @PeteWilliams @mattrussell36

**Comment by PeteWilliams** [comment]
Looks good @bigfandavid. Wasn't expecting it to be white on the dark theme, but don't have a problem with it as it stands out nicely.
