### ISSUE TITLE
Create new test workflow for stagnet1

### ISSUE THREAD

**Issue by jtsang586** [vegaprotocol/frontend-monorepo#1729]
## The Chore

Moving forward `Stagnet1` will be used as a staging environment for testing new releases before getting deployed to Testnet.

We want to create a new workflow which will allow us to manually run all E2E tests against Stagnet1 to give us confidence to deploy new releases onto Testnet.

- Create a new workflow which can be triggered manually to run all tests against stagnet1
- There is a closed PR which was created for running tests against stagnet 3. This contains a script to copy all the environment files to whichever environment we choose.
https://github.com/vegaprotocol/frontend-monorepo/pull/1319/files

**Comment by jtsang586** [comment]
This is blocked until we have a url available to stagnet 1 block explorer
https://github.com/vegaprotocol/devops-infra/issues/1548

**Comment by pennyandrews** [comment]
Checked with Joe and he confirmed that there's not been a need for this since we've started using stagnet1 so all good to close. And with the way capsule is dockerized now, it's not trivial to change the version of core to run tests with so I don't think it's worth the effort unless we really need this
