### ISSUE TITLE
Dont require Ethereum connection to display collateral

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/frontend-monorepo#1812]
## Story

**As a** trader
**I want to** be able to see my collateral without connecting my Ethereum wallet
**So that** I am not blocked from reviewing collateral for trading

## Acceptance Criteria

- [ ] I can see my collateral without an Ethereum wallet connection
- [x] I am prompted to connect my Ethereum wallet when depositing
- [x] I am prompted to connect my Ethereum wallet when withdrawing

## Additional details / background info

This table is currently wrapped with the Web3Container component to allow the withdraw/deposit dialogs to opened from within. Some refactoring will be required to only prompt for Ethereum connection when opening these dialogs.

**Comment by PeteWilliams** [comment]
I'm presuming that if you've made existing deposits/withdrawals, we're able to see them without connecting your ethereum wallet, as we have the data on the Vega side.

AC1: I can see my collateral without an Ethereum wallet connection
Remove the 'Connect ethereum wallet' state.

AC2: I am prompted to connect my Ethereum wallet when depositing
Already seems OK? Doesn't have the 'connect wallet' state in the tab, but clicking Deposit launches the 'Connect your Ethereum wallet' dialog before you get to the deposit dialog.

AC3: I am prompted to connect my Ethereum wallet when withdrawing
Should be same as deposit - no 'Connect ethereum wallet' tab state but launches 'connect wallet' dialog when you click Withdraw.

Related: https://github.com/vegaprotocol/frontend-monorepo/issues/1271 - No way of disconnecting from Ethereum wallet in Console

**Comment by mattrussell36** [comment]
@PeteWilliams yeah so second two ACs are already handled and a similar approach will be taken for the collateral table. However, I think the particular flow of connecting your wallet to deposit/withdraw is a little clunky and could use some design thinking.

**Comment by PeteWilliams** [comment]
@mattrussell36 it is a bit clunky, but that's the nature of the process - you _have_ to connect two wallets before you can deposit.

We could potentially just go straight to the withdrawal/deposit form and then have buttons to connect the wallets if they're not connected:
![image](https://user-images.githubusercontent.com/1325606/201133667-8f9beb73-2a83-4347-9f6d-1ac12910749f.png)

I think there's _some_ benefit to this, in that you at least get to the form you were expecting to see, and know what you need to proceed. But there's also something to be said for just handling one task at a time rather than giving them a form they can't yet complete.

I also notice that when you click the deposit button, there's currently an additional modal:
![image](https://user-images.githubusercontent.com/1325606/201135059-908d5882-c3f0-4e1d-82c2-07cf8f8edbf7.png)

Unless this serves a purpose, we could just skip to this one: 
![image](https://user-images.githubusercontent.com/1325606/201135209-4794387c-316f-4600-afab-ec5bc3e531f6.png)

Or even better, are we able to detect if they are running Metamask and skip both the above screens if they are? 

Similarly for the Vega wallet modal, it'd be nice if we could skip the below screen if we can tell if they have a wallet running locally and what type it is.? 
![image](https://user-images.githubusercontent.com/1325606/201135361-7add7ddc-67b5-4caa-8bd5-d3ade1aa7434.png)
