### ISSUE TITLE
Type generation fails

### ISSUE THREAD

**Issue by edd** [vegaprotocol/frontend-monorepo#2023]
#2022 partially fixes the problem. Removing `console-lite` is another approach. But neither fix the underlying problem.

# To recreate
```bash
export  GRAPHQL_SCHEMA_PATH=https://api.n11.testnet.vega.xyz/graphql
yarn nx run types:generate
```

```sh
Loading Apollo Project [failed]
→ Error initializing Apollo GraphQL project "vega": Error: Error in "Loading queries for vega": Error: ️️There are multiple definitions for the `MarketTags` operation. Please rename or remove all operations with the duplicated name before continuing.
 ›   Error: Error initializing Apollo GraphQL project "vega": Error: Error in
 ›   "Loading queries for vega": Error: ️️There are multiple definitions for
 ›   the `MarketTags` operation. Please rename or remove all operations with
 ›   the duplicated name before continuing.
```

# Tasks
- [ ] Make type generation function again

**Comment by macqbat** [comment]
#2022 did nothing related to console-lite. There are several not migrated yet components and their queries and some of console-lite are ones of them. You can remove console-lite, but also you will have to remove few other components or modules. There is a big mess in typing in repo now due to fragmentary chaotic migration

**Comment by mattrussell36** [comment]
This has been fixed.
