### ISSUE TITLE
Saving space on the vertical and other design changes

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2037]
## Chore

There have been a few comments on the vertical space taken up by different UI components in console - this chore is to look at the patterns used and identify any areas to tighten things up, for example...

* Status bar doesn't have to be full width, visible all the time, nor does it have to be in the bottom of the screen 
* Header could transition out / have some kind of collapsing behaviour 
* Padding around list items could be looked at, headers, tabs
* We could find a different approach to things like the 'cancel all' button on the orders tab which currently has a whole row of vertical space just for a button

**Comment by PeteWilliams** [comment]
# Spacing

## Market header

**Current**

![Image](https://user-images.githubusercontent.com/1325606/202497372-b4e89837-054e-4b24-afb5-a19ea8e2cb68.png)
![Image](https://user-images.githubusercontent.com/1325606/202497415-d7f62c6b-793b-4848-b2eb-78e316530250.png)

**Proposed**

- Remove the gap between the market header and the nav.
- Prevent market name and details from wrapping too soon.

![Image](https://user-images.githubusercontent.com/1325606/202497477-f77bbcf3-8a2e-4fc7-9fa6-ad7986ad5fd6.png)


## Tabs

**Current**

![Image](https://user-images.githubusercontent.com/1325606/202497544-f35e81f5-3b78-4245-92fe-a9a8d27c0a6d.png)


**Proposed**

- Change tab padding to py-1

![Image](https://user-images.githubusercontent.com/1325606/202497609-1c010605-81f0-4aa0-8dd1-6f2b35c47700.png)



## Status bar

**Current**

![Image](https://user-images.githubusercontent.com/1325606/202497661-42a59a81-edaa-4f1b-8e9e-3c03513fbad0.png)


**Proposed**

- Discuss what the user needs for this are, then work out the best solution from them. Some info might go elsewhere so we can lose the status bar, or maybe we could make it collapsable. 

- Maybe something along these lines?

![Image](https://user-images.githubusercontent.com/1325606/202497716-775ea65b-8eac-4816-a4ef-a859d06e6b70.png)

![Image](https://user-images.githubusercontent.com/1325606/202497765-bb26cee3-a75d-4b9a-af40-ca943517aba3.png)



## Multi-row tables

Eg collateral or positions

**Current**

![Image](https://user-images.githubusercontent.com/1325606/202497816-de29e24d-4ebf-4fa9-b478-0a0160eb252a.png)


**Proposed**

- Change row height to 32px
- Change padding on the liquidation bar to mt-1
- Remove total row - doesn’t work if you have different assets above

![Image](https://user-images.githubusercontent.com/1325606/202497868-4f290073-c20b-480a-a1b0-d9c048bb4ef6.png)



## Single row tables

**Current**

![Image](https://user-images.githubusercontent.com/1325606/202497891-684dddf6-4c7b-4cb4-9c02-24f51d998070.png)


**Proposed**
- Change row height to 24px

![Image](https://user-images.githubusercontent.com/1325606/202497944-5f7380c6-3d89-4be7-ad82-d3f078f2129c.png)



## Table footer buttons

**Current**

![Image](https://user-images.githubusercontent.com/1325606/202498219-2ac678ea-a1fc-4ab6-922e-64a80527ea98.png)

**Proposed**
- Make deposit/withdraw/cancel all button float in the bottom right of panel.
- Make it a secondary button
- Add sufficient padding to the bottom of the collateral panel so that you can always scroll to see last row in full.

![Image](https://user-images.githubusercontent.com/1325606/202498012-1619fb4f-a98c-4fcb-a412-0fa476da0403.png)

![Image](https://user-images.githubusercontent.com/1325606/202498035-960e2e0a-ac9f-49e3-9b11-270f2431fb98.png)



## Ticket

**Current**

![Image](https://user-images.githubusercontent.com/1325606/202498312-2e071c63-02bc-4684-8dc2-1c72cc70018d.png)


**Proposed**

- Field labels
    - reduce margin to mb-1
    - change text to medium weight and uppercase
- Field spacing - reduce margin between fields to mb-4
- Input field padding - reduce to p-1
- Submit button padding - reduce to py-1

![Image](https://user-images.githubusercontent.com/1325606/202498345-9945ef7a-a4e6-45b4-8e4b-2cd65407dc10.png)



## Market info /accordion

**Current**

![Image](https://user-images.githubusercontent.com/1325606/202498419-d6388335-ff44-4d1c-9cc8-d29dadc013bb.png)

**Proposed**

- Section heading (eg ‘market data’) -  change to text-m, mb-2
- item label (eg ‘current fees’) - change to py-1, font size 15px
- Accordion content - reduce py-4 to py-1
- Key value table - remove mb-4
- Accordion block - reduce mb-8 to mb-6

![Image](https://user-images.githubusercontent.com/1325606/202498483-ea33a1a3-d877-49c8-85dd-315c1f0b8efa.png)

**Comment by bigfandavid** [comment]
Hello! 2nd attempt at writing this... clearly not going to be a good as my first...

As you're aware I've spent time looking at Console and finding opportunities for improvement now that we've lived with the new design for a little while. Joelle and I jumped on a call this morning so I could walk through all of the changes and we're both happy so time to put this out to the group!

You can find the Figma file here: https://www.figma.com/file/deV7EBxvTF4ggdsKVVosfr/Console-V2---Design-Revisions?node-id=925%3A4915&t=EPYT7Ijad7wKuiW2-1

You'll land on the proposed new design. To the left of this are screenshots of what is currently live and on the right is the last iteration of the design that lives on Figma.

---

Through this piece of work I've looked to address the following, some of which spill into other Chores/tasks:

- **Vertical spacing** - Here is a before/after visual of the Ticket panel, which demonstrates the tweaks I've made to spacing well. The whole design now utilises our horizontal spacing tokens from the Design System.

![Image](https://user-images.githubusercontent.com/113683891/206219152-a4f434fe-1f18-4ebf-929f-b19121660de5.png)

- **Colour updates** - Mainly the introduction of Vega pink, in place of the red to make this more on brand (general agreement from Barney and Matt that we can do this!)

- **Contrast of dividers/design elements** - We've actually _decreased_ contrast across dividing lines and some type styles to make the whole design more intuitive. I took my lead from the likes of dydx on this. It really allows us to draw focus to the information that matters and makes the design as a whole more visually pleasing (all the light dividers were very distracting).

- **Typeface update** - Alpha Lyrae now implemented. I'm keen to commission a zero with a dash in for Console, but no biggie.

- **Link/button styling (request from Matt)** - I've introduced a new mini text-link which comes in two forms: sentence case and UPPERCASE (with icon). This can be seen throughout the design, but here's a snapshot:

![Image](https://user-images.githubusercontent.com/113683891/206221311-c74f304c-12af-4cbb-9738-56ea4d465dc7.png)

![Image](https://user-images.githubusercontent.com/113683891/206221312-fc754e64-b84b-4a76-9f8e-09de174aebac.png)

---

There are some other design tweaks which Joelle and I have discussed and will be updated in the UI Design System.

Perhaps worth discussing all this in the design crit tomorrow?

Thanks!
David

**Comment by mattrussell36** [comment]
This work as been superseded by design changes epic
