### ISSUE TITLE
Show active liquidity committed only

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2191]
## Chore 

We need to filter for LP status - right now we are showing committed liquidity for active AND inactive together which is giving us very high numbers. **Instead committed liquidity numbers should only be for active LP providers.** You can see here for example there are active and inactive commitments https://console.fairground.wtf/#/liquidity/ad2e531441c2e8a43e85423db399a4acc8f9a8a2376304a4c377d0da8eb31e80

![Image](https://user-images.githubusercontent.com/46783148/203296858-55a47fc7-712c-48e5-8cdb-54086788ec04.png)

![Image](https://user-images.githubusercontent.com/46783148/203297125-344caeb0-9e47-4e30-ad92-bc4477cb7358.png)

**Comment by ciaran-** [comment]
We think there might be a bug in the core API here which would be the resolution. I've attached a [thread on Slack](https://vegaprotocol.slack.com/archives/CFXA4EGN7/p1669291824594749) where @JonRay15 mentioned he'll follow up with some folks and get back to us. 

In the meantime I'm going to leave this one. If we need to, we can look at summing up the `status: "STATUS_ACTIVE"` provisions, but I don't think that's the right thing right now.

**Comment by ciaran-** [comment]
Ok, so my previous comment is now out of date. We think this was because some of the provisions were _undeployed_ - which 
Barney describes below:

![Image](https://user-images.githubusercontent.com/6756742/203792491-e6168301-b0f1-4914-abde-550663b87be3.png)

Once @JonRay15 added some priced limit orders, we saw the LP health of those markets improve. 

Barney also confirmed/suggests that undeployed LP orders _should_ be included in the 'commited stake' we display, so I think there's no action to take here - other than to say that these markets were in an unusual state when we were looking at this before.

**Comment by ciaran-** [comment]
@ckpringle make sense?
