### ISSUE TITLE
Time left and age e.g. "Settles in 7 days" "Market is 3 months old"  * 

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2216]
## The Chore

Add in the duration the market has left and the age of the market.

## Acceptance criteria 

* I can see for each market how old it is 
* I can see for each market when it settles 

## Tasks

- [ ] Ask from the frontend team if the market settlement date / timestamp is only in the governance API / has anybody already pulled this out via integration somewhere e.g. "expiry" in console
- [x] Implement market age "market is 6 days old"
- [ ] Etc.

**Comment by ciaran-** [comment]
Yeah so I think we might need to either use another API for this or request additional data on the market one.

Looks like most `Market`s I can see have `null` for the `close` property - and given the conversation on https://github.com/vegaprotocol/frontend-monorepo/issues/2219 it seems like this means when they _have closed_ rather than when they _will_ or _intend_ to close. 

It's possible I've got the wrong end of the stick here, though!

**Comment by JonRay15** [comment]
Did we work out how to get this?

If not do we need to ask Core? And should it be in Console too?

**Comment by ciaran-** [comment]
Hi @JonRay15 - I was working from the assumption that we'd need to grab this from the governance API, so that's what I was working towards grabbing this morning.

Very happy to ask Core if we think it should be on the Market though

**Comment by barnabee** [comment]
The reason the field you pulled is only on the governance API is because it contains the date/time that voting on the proposal closes and is not a settlement or maturity date or time for the market.

For settlement date/time there is no such field as there is no guarantee that a market will have a specific settlement date time. If such data exists and is valid then an optional metadata tag would need to be used on the market, and the convention for this should be agreed in the community, and might be a tag that looks something like `settlement_data:2023-12-31 23:59` or whatever.

**Comment by barnabee** [comment]
> Looks like most Markets I can see have null for the close property - and given the conversation on https://github.com/vegaprotocol/frontend-monorepo/issues/2219 it seems like this means when they have closed rather than when they will or intend to close.

This is correct.

**Comment by ciaran-** [comment]
Ah, ok great thanks @barnabee think I've got a much clearer picture now.

@ckpringle that might scupper this column then? Shall I rip it out?
