### ISSUE TITLE
Display subsets of "opening auction"

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#2524]
## Chore 

We want to show two subsets of opening auction: "Opening Auction: Not enough liquidity" and "Opening Auction: Closing on `enactmenttimestamp`"

## Acceptance criteria 

* Wherever there is currently an opening auction status, there is a way to understand why the market is in opening auction e.g. "not enough liquidity" or "closing soon"
*  If the opening auction is closing soon, I can see when that is "Closing on `enactmenttimestamp`"
* For "not enough liquidity" there is a mouseover: "This market is in opening auction until it has reached enough liquidity to move into continuous trading."
* For "closing on..." there is a mouseover: "This is a new market in an opening auction to determine a fair mid-price before starting continuous trading."

## Background 
Outcome of spike https://github.com/vegaprotocol/frontend-monorepo/issues/2219

How to work out what status to display: 

If status = opening auction and TODAY > enactmentTimestamp then status = Opening Auction : Not enough liquidity to open
else status = Opening Auction : Closing on enactmentTimestamp

Data available in governance API e.g. (this is fairground) https://api.n06.testnet.vega.xyz/api/v2/governance?proposalId=de48ad0adc668a80a074e790d118b6a64fa4909fc60ebbc2c335be3b675fec93

**Comment by JonRay15** [comment]
I raised this to Core and it was publicly concluded (with Barney backing) that even though we might have to do this in a couple of places, it doesnt make sense to add it to Core because it is fully derivable based on info they already provide.  So we will need to at some point build this code and make it available to Console so they can utilise it too. 

In any case I am happy this doesnt need to be in MVP; therefore moving to unblocked and putting in the backlog.
