### ISSUE TITLE
Trading mode in market selector and header do not match

### ISSUE THREAD

**Issue by MadalinaRaicu** [vegaprotocol/frontend-monorepo#2530]
Trading mode in market selector and header do not match.
Reproduce: Go on console testnet and switch between  BTCUSD and UNIDAI markets

![Image](https://user-images.githubusercontent.com/16125548/210798259-d43b842e-a784-4f7b-b3f8-9352b2688c4c.png)

![Image](https://user-images.githubusercontent.com/16125548/210798244-f30437b3-ea00-473f-a1cd-febf6c9e95ca.png)

**Comment by MadalinaRaicu** [comment]
@macqbat  mentioned that in the market selector only one market gets live updates - the one which is selected on the market page. 
Perhaps marketList query in market selector gets some weird, wrong cache, and each time the user open the market selector we should do a new query to refresh the list.

**Comment by bglownia** [comment]
We are reloading each time user opens `<SelectMarketPopover>`
Every time user opens it three queries should be executed through data providers : markets, markets data (for all markets, without subscription - snapshot), candles (since: yesterday, interval 1h).
Additionally if market id matches one stored in global store MarketMarkPrice, Last24hPriceChange, Last24hVolume, MarketTradingMode should be taken from market data subscription for selected market.
