### ISSUE TITLE
Include proposal rationale title and description in JSON block

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/frontend-monorepo#3581]
## Description

Rationale title and description are not visible in the "Proposal terms" JSON on the proposal details page. Considering the JSON is a way to see the "raw" proposal submitted, the expected behaviour is that this information would be included there. 

## Steps to reproduce

1. Go to a proposal - note the title and description (which is beside the proposal type label) 
2. Scroll down to the "Proposal terms" section and see it's not there

## Screenshots

<img width="846" alt="Screenshot 2023-05-02 at 16 33 31" src="https://user-images.githubusercontent.com/46783148/235714081-8b28bb73-d49b-4d8a-8bff-c98091cbd4b0.png">

**Comment by sam-keen** [comment]
@ckpringle the work on this ticket depends on what you're really after - the rationale doesn't sit inside the proposal's 'terms', it's its own separate value (of which there are many we don't show - party, state, votes, datetime, rationale). We show everything that comes down the pipe within the proposal's terms value. We show the terms because we haven't yet put in the time to make sure we display everything nicely in tables. Barney's recently said we need to (https://vegaprotocol.slack.com/archives/C038EB6V2RE/p1683889039913589?thread_ts=1683825029.555719&cid=C038EB6V2RE) so this ticket may be redundant

**Comment by JonRay15** [comment]
So I guess then we'd end up with properly rendering the relevant details in a nice way, and then this part should just become the full raw JSON for any technical types that wanted to review it?  Rather than specifically cherry picking the "terms"?

That would make sense to me if that was the approach.  If we do that I guess we'd need some new tickets for the proper rendering.

**Comment by ckpringle** [comment]
Ok capturing as a separate ticket - https://github.com/vegaprotocol/frontend-monorepo/issues/3778

**Comment by JonRay15** [comment]
This is already done under https://github.com/vegaprotocol/frontend-monorepo/issues/3778 ... closing
