### ISSUE TITLE
My Stake green highlight doesnt light up for pending stake

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#3680]
## Description

You get the green text on your pending stake column which is nice.

But really it should presumably also light up the My Stake button over the STAKE button.

At the moment it doesnt, and therefore it also doesnt appear if you set the toggle to Staked by Me

## Steps to Reproduce

1. Go to validators
2. Click on STAKE and add some stake to someone
3. You will see some pending stake 
4. But you wont see the other things I mentioned

## Expected behavior

MY STAKE shoudl light up and be included in the toggle

## Screenshots

<img width="1035" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/853f6ac3-fa81-4e37-af85-a2b5f58ff6b8">

<img width="1057" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/90f46eec-0156-403b-9a0b-daa76fa97aff">

**Comment by pennyandrews** [comment]
@JonRay15 this is by design. The green indicates the things that are specific to me. And My Stake is what I have staked this epoch, which is why the stake button for PathrockNetwork isn't green because you don't have anything staked for them this epoch. Next epoch, you would have a green my stake button. 

We are pretty comfortable this makes sense, but will keep an eye out for feedback from anyone else that indicates this is confusing 👍
