### ISSUE TITLE
Add date / time selector to proposal generator

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#3731]
## Story

As a proposer
I want a datetime selector not the weird duration setter
So that I dont get a constantly changing timestamp that is confusing and requires me to hit a precise value if I want a round number

## Acceptance Criteria

- [ ] I can select the date and time that I want it to enact from some datetime picker thingy
- [ ] I can see how far away that is 
- [ ] I am warned if that duration is less than the min duration or is within say 2 hours of that duration to give time to finish the proposal

**Comment by JonRay15** [comment]
This may be a dupe ...

**Comment by sam-keen** [comment]
@JonRay15 A datetime selector isn't an ideal element - the 'constantly changing timestamp' is the way the proposal's limits actually work. They're based on a fixed amount of time away from 'now', defined by a network param. Therefore, using a datetime selector to try to choose the minimum value will automatically get declined when the proposal's submitted, because by the time the user's hit the 'submit' button, the selected value will now be closer than the updated minimum.

**Comment by sam-keen** [comment]
We discussed this one previously @ckpringle, I think it needs some UX love
