### ISSUE TITLE
total staked

### ISSUE THREAD

**Issue by rebeccajsimmonds** [vegaprotocol/frontend-monorepo#3771]
## Description

The total staked number on the block explorer home page is different from the total staked on the website homepage and interestingly also different from the total on the nodes guru validator summary tool https://stake.nodes.guru/vega/world

## Steps to Reproduce

1. Go to https://vega.xyz/, https://explorer.vega.xyz/, https://stake.nodes.guru/vega/world
2. See 3 different totals for total staked

## Expected behavior

If they numbers cannot be the same I would expect to see an explanation of what is included in the number

**Comment by edd** [comment]
* vega.xyz being different to block explorer will be fixed by https://github.com/vegaprotocol/vega.xyz/issues/573#event-9247744307
* stake.nodes.guru might be implementing their count differently from the way I do it. I trust the API endpoint, which might not have existed at that point. Block explorer uses this:

```graphql
{
  nodeData {
    stakedTotal
  }
}
```

Which returns a different number to querying for all nodes, and totalling the value.
