### ISSUE TITLE
Health bar numbers issues

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4118]
We fixed some decimals issues on the main columns but some of these persist _within_ the healthbar. 

The heathbar seems to have two hover-overs.

### Target Stake line 

This one seems fine. It matches target stake, but we should remember to check this picks up quantum formatting when we do that. 

### Over a block of liquidity 

These are hard to interpret currently because there is only one commitment on each one.

1. The LP Fee is incorrectly formatted .... needs to be x 100. 
2. I'm not sure what the second part is showing.  
    a. For BTC & LINK markets it seems to show the supplied stake, but it looks like it needs to be formatted with `asset decimals` and isnt. 
    b. For ETH its doing something else. The decimals are wrong but its also showing 32,320 instead of 50,000...and I have no idea whatsoever where it is getting that number! 

![Image](https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/47f5333b-c769-4b67-8024-39f0e0b235b3)

**Comment by JonRay15** [comment]
PR to go onto monorepo and then onto website later today

**Comment by ciaran-** [comment]
<img width="280" alt="Screenshot 2023-06-27 at 10 39 32" src="https://github.com/vegaprotocol/frontend-monorepo/assets/6756742/82e5cb8b-d833-42ef-8943-a42a17c2546e">
The fix for this introduced a visual bug that I'll address - the target stake line's tooltip is always showing text in black - regardless of light/dark mode, which in the default dark mode makes it basically impossible to read.
