### ISSUE TITLE
Liquidation story telling

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/frontend-monorepo#474]
Requires discussion to see what is needed and what support we have in the back end / what may become a request to the back end.

A possible stopgap idea could be: 
Linking to BE and show a position page to show one was liquidated, as this may break the dependancy on the data-node would should there be any (and time permitting)

**Comment by PeteWilliams** [comment]
Initial thoughts here:
https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=2276%3A30549

A toast would be shown when loss socialisation occurs:
![Image](https://user-images.githubusercontent.com/1325606/177307896-4349d506-cc0d-4d6a-a7f5-756763382167.png)

And then shown under the history tab:
![Image](https://user-images.githubusercontent.com/1325606/177307956-c760a2df-2d66-416d-927b-8bcdf79c283d.png)

**Comment by PeteWilliams** [comment]
There's three elements to this story telling,

The positions table updated covered in https://github.com/vegaprotocol/frontend-monorepo/issues/473
![image](https://user-images.githubusercontent.com/1325606/181465924-9ca6ac97-58d2-4740-ad07-004cd43f4388.png)

Then there's the [toasts](https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=2277%3A32814) which we will leave for now due to the complexity involved.

And then there's the matter of showing the transactions in the history panel which is dealt with in https://github.com/vegaprotocol/frontend-monorepo/issues/846

So I think this can be closed.

**Comment by mattrussell36** [comment]
I'm happy with this being covered by the ledger entries table
