### ISSUE TITLE
Overlapping candles on chart

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/frontend-monorepo#4768]
## Description

We have overlapping candles on the chart, which is bad.

## Steps to Reproduce

1. Go to LINK market on mainnet (update: its on all 3 actually)
2. Look at it
3. See overlapping candles (and screeshot)

## Expected behavior

The open / close on two adjacent green candles should nmever overlap, it doesnt make sense. Since candle is only green if close > open it shoud be impossible.

## Screenshots

<img width="804" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/885b8814-defc-45dd-9b6f-ae855f128da9">

## Tasks

- [ ] Create poc for comparison
- [ ] Share with the team

## Device details

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome

**Smartphone (please complete the following information):**

n/a

**Comment by mattrussell36** [comment]
@JonRay15 @barnabee I don't actually see any overlapping here, I think the reduced gaps between candles and the zoom level is making it appear that the candles are touching.

**Comment by barnabee** [comment]
@mattrussell36 I think you are misreading the ticket - it is about the open and close levels (bottom and top of fat part respeectively, for an upward move) not horizontal width and placement.

**Comment by barnabee** [comment]
So IIRC the definition of a candle has the following features to display `open`, `high`, `low`, `close` data:

**Wick (thin part):**
- top of wick above candle = `high` (highest price printed on any trade during the period)
- bottom of wick below candle = `low` (lowest price printed on any trade during the period)
- (invisible on either side of the highest/lowest price == the appropriate one of open or close)

**Body (fat part):**
- hollow IF `close` (last trade IN period) > `open` (first trade IN period)
- filled IF `close` < `open`

**Candle colour:**
- green if `close` (this period) > `close` (last period)
- red  if `close` (this period) < `close` (last period)

So the bug is pointing out that a green candle's body can never overlap another green candle's body. Separately, I am not sure that pennant applies the hollow/filled logic at all.

**Comment by barnabee** [comment]
On TradingView you can switch the type to "hollow candles" rather than candles and you'll see that where the `open` <> `close` direction and the `previous close` <> `close` direction differ you get a hollow red or filled green candle:

<img width="1195" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/1179257/91c5425f-4069-4ed4-836f-130aedba4001">


It would be nice for us to support this (as an additional chart type in the dropdown), as well as fix the colouring of the default view. I'd imagine such support would be quite simple given there's no change to the rendering logic only colours and filled or not.

**Comment by JonRay15** [comment]
I dont think we know the correct thing here .... this feels like it needs some more investigation and research, and also could be solkved by having a setting to toggle behaviour.

**Comment by barnabee** [comment]
@JonRay15 I agree we aren't 100% sure what we want for the normal default filled candles behaviour.

Also think the full "hollow candles" new chart type per [the definition at the start of this comment](https://github.com/vegaprotocol/frontend-monorepo/issues/4768#issuecomment-1718664144) can be split out into a second ticket and that _is_ well defined and could be built if we wish (IMO it'd be cool but not essential, perhaps if we had resource to work on Pennant and not much else to do there).
