### ISSUE TITLE
Governance site proposal previews

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/frontend-monorepo#5260]
A real nitpick: when I link to a specific proposal the preview just mentions the governance dapp page; could it be changed to the proposal title or something?

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/62546419/c7b8bab9-d5dd-4274-9ccd-7e83a3941f47)

## Tasks

- [ ] Ask @candida-d for some words
- [ ] Set the 3 tags to be different text as a quick win

**Comment by mattrussell36** [comment]
Getting this to work for individual proposals would mean a architectural change to a statically generated website. Its very unlikely we'd want to spend time on that right now.

We can certainly take a look at updating the default meta tags so that its not repeating 'Vega protocol - Governance' three times though
