### ISSUE TITLE
View proposed network changes

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/frontend-monorepo#579]
**As a** console user
**I want to** see where there are proposed changes to network parameters in context in console
**So that** I know what's being proposed, can understand potential impact and and easily go vote for or against the changes without having to keep an eye out for proposals somewhere else

**Comment by PeteWilliams** [comment]
Looks like toasts will soon be released so would be good to use them for this.
So when you switch to a network that has changes, or when you log in and there has been a new proposal since your last visit, we tell you in a toast:

![image](https://user-images.githubusercontent.com/1325606/201368257-b6f61a04-27f6-46b9-baf0-1caf152dbb59.png)

I don't think we have a ticket for showing that changes have gone live, but I think it makes sense to also let users know then:

![image](https://user-images.githubusercontent.com/1325606/201369163-a119a592-22fd-4971-af04-3f328e6dbbb7.png)

**Comment by pennyandrews** [comment]
Matt feels that toasts should go in the bottom right, others think top right? Will need to discuss this in Friday's toast kick-off meeting.

**Comment by PeteWilliams** [comment]
I think it should definitely be top right, bottom is too easy to miss. Top right is standard pattern for notifications in MacOS etc.
