### ISSUE TITLE
Show Asset details (ID, contract address) in console

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#627]
As a trader I want to be verify that the asset on Vega known as XYZ is the same XYZ that I know from Ethereum.
... I want to quickly copy the asset ID to help with API use (market proposals, etc)

```
{
  assets{
    id
    name
    symbol
    decimals
    quantum
    totalSupply
   
    source{
      ...on ERC20{
        contractAddress
        withdrawThreshold
        lifetimeLimit
      }
    }
      
    globalRewardPoolAccount{
      type
      balance
      market{
        id
      }
    }
  }
}
```

I suggest that the global reward detail are left to display on Token site (as this is where reward info site. but could also appear in console

As a trader wanting to asset how popular a Vega network is I might also want to know how much of a given asset is deployed on Vega (perhaps with a break down of the account types it resides within), better still to see this over time. However, at the time of writing the API for this has not been implemented. https://github.com/vegaprotocol/data-node/issues/43

**Comment by PeteWilliams** [comment]
Proposed design:
https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=2557%3A31822

Asset info is to be displayed in a modal, because it can be accessed from multiple locations:

![Image](https://user-images.githubusercontent.com/1325606/180969655-1c845c3c-12e1-4f06-b42e-150fa1ed2a85.png)

The content for the tooltips is as per the [docs](https://docs.fairground.vega.xyz/api/grpc/):

```
name			
Name of the asset (e.g: Great British Pound)

symbol			
Symbol of the asset (e.g: GBP)

total_supply			
Total circulating supply for the asset

decimals			
Number of decimal / precision handled by this asset

quantum			
The minimum economically meaningful amount in the asset

contract_address			
The address of the contract for the token, on the ethereum network

lifetime_limit			
The lifetime limits deposit per address note: this is a temporary measure for restricted mainnet

withdraw_threshold			
The maximum allowed per withdraw note: this is a temporary measure for restricted mainnet
```


The modal can be opened from the following locations:

*Market header*
![Image](https://user-images.githubusercontent.com/1325606/180970130-fb7e108e-5af4-4155-9bc3-4540bd41318d.png)

*Deposit form*
![Image](https://user-images.githubusercontent.com/1325606/180970002-d0ca11ca-5e08-4634-8604-d8215442e82c.png)

*Collateral tab*
(Only show underline on row hover)
![Image](https://user-images.githubusercontent.com/1325606/180970209-e0704ba3-788b-42f4-9427-462fecbc018f.png)

*Market list*
(Only show underline on row hover)
![Image](https://user-images.githubusercontent.com/1325606/180970303-8b8ea6a3-f508-49a5-9b4d-053813721015.png)
