### ISSUE TITLE
Bug with deal ticket size input.

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/frontend-monorepo#6595]
## Acceptance

- [ ] Disable something that makes it zoom

## Original ticket

When I select the size input on mobile, the UI gets fucked (see screenshot)
![IMG_0605](https://github.com/vegaprotocol/frontend-monorepo/assets/4346460/2577e475-67a1-42e0-a151-43a85aed46c4)

**Comment by JonRay15** [comment]
This is impacting ability to manage trades from mobile ... say for instance if someone was in a field for a weekend .. so can it be patched on main please?

**Comment by JonRay15** [comment]
The datanode selector also has disappeared from mobile completely. 

There is work on #6465 to find a home for this that Art is working on now, so either we could fast track that into main too, or we could as a short term solution put the selector in the header for now (since this shoudl work easily for mobile too) and then move it later once he has something more agreeable.

**Comment by JonRay15** [comment]
This is fine ... and you can always zoom out too.
