### ISSUE TITLE
Panel resizing tweaks

### ISSUE THREAD

**Issue by PeteWilliams** [vegaprotocol/frontend-monorepo#819]
The [new panel resizing](https://app.netlify.com/sites/vega-trading-app/deploys/62d5620732234e000863f70b) works nicely, but it'd be nice if we could use it with the original panel border design.

Current:
Uses a single pixel grabbable border.
<img width="166" alt="image" src="https://user-images.githubusercontent.com/1325606/179805548-3707588a-dcff-4a00-8fa5-408412498b95.png">

Original design:
Uses an 8px border.
<img width="125" alt="image" src="https://user-images.githubusercontent.com/1325606/179805639-9759f1eb-5d8f-4ffc-b82f-e985a47bc7e7.png">

This may be as simple as setting [setSashSize(8)](https://github.com/johnwalley/allotment#styling) but I couldn't get that to work.

Note I've already committed [some minor tweaks](https://github.com/vegaprotocol/frontend-monorepo/compare/chrore/ui-tweaks?expand=1) to adjust the layout and behaviour in the `chore/ui-tweaks` branch. Not sure what the etiquette is - let me know if I should do a separate PR for that, or if whoever takes on this ticket wants to just continue that branch…?

Changes in that branch:

- Adjust panel sizes
- Prevent bottom panel snapping to closed
- Setting minimum height for bottom panel so it can't be 'lost'
- Added back horizontal line above tabs to separate the content
- Set border colours for light/dark theme

**Comment by johnwalley** [comment]
This is similar to the #1 feature request:

- https://github.com/johnwalley/allotment/issues/280
- https://github.com/johnwalley/allotment/issues/253

It is not something VS Code supports. In fact, what Allotment should really be doing is providing no separator at all (currently it is 1px wide/tall) to replicate VS Code exactly. It would then be up to the consumer of the library to provide a separator.

I've said no to this feature so far as it's a substantial change and I don't have the free time to work on it. However, if Vega would be paying me to implement it then I can justify the time to work on it. It's particularly impactful because it means the library is no longer a straightforward React port of VS Code's split-pane component and would be more its own thing. Which isn't necessarily a bad thing, it's more that I'm not sure I have the time to maintain it when it's not just a case of porting VS Code to React.

Back to the specific issue. The previous CSS used the grid gap property to put in a 'border' between grid elements. But crucially, not around the outside of the grid elements. Otherwise we could simply use padding/margin for the content of the panes and be done.

To get even more specific, there are two possible things we want here:

1. a 'border' between panes
2. the border should be the same size as the interactive drag element (the sash in VS Code terminology)

The current separator is an absolutely positioned pseudo element. In other words it won't push the content out of its way, it will just overlap it. This is why just increasing its size won't help.

I appreciate there is some technical detail and jargon involved. It's one of those things which is easier to show than to tell; so am happy to demo over zoom if anyone is interested.

**Comment by johnwalley** [comment]
Taking a step back. It would be sensible to assess a few other React split-pane libraries because they might give us this for free. I've no horse in this race 🐴.

The other approach would be to style it more like VS Code. Then there would be no need to add wider 'separators'. Just a thought!
