### ISSUE TITLE
Portfolio: Ledger entries enhancements

### ISSUE THREAD

**Issue by PeteWilliams** [vegaprotocol/frontend-monorepo#846]
### Proposed design
https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=1616%3A26257

![image](https://user-images.githubusercontent.com/1325606/180467984-583bb5ad-d8e7-4d73-90f9-03e6707c7f23.png)

### Details
Intention is that this tab shows the transactions you didn't explicitly make - liquidation, fees paid/received, search/release levels being hit, etc. - current thinking on title is Ledger entries

**Comment by candida-d** [comment]
@PeteWilliams I've had a few ideas but nothing I particularly like so I'm keeping them to myself for now. 

However I've had another thought. Could the event & action columns be combined? They come across to me as a bit "developery" versus more user-centric. I don't know if this is limited based on the API or otherwise but I think it could do more work for users. What do you think?

**Comment by barnabee** [comment]
Just a note that I really don’t think we should call these system _transactions_ in the UI. They are all part of processing user transactions, like everything occurring on chain and I think the nomenclature will be really confusing.

They are called ledger entries in the API, they could also be internal transfers, ledger transfers, etc. but I suspect being consistent with the API is the right plan.
