### ISSUE TITLE
Deal ticket should not show a price for market orders when market is in auction

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/frontend-monorepo#991]
![Image](https://user-images.githubusercontent.com/13255539/183844218-e14e3e74-234a-4b48-931a-0923712de09e.png)

In this scenario the market is in liquidity auction, I think it is very misleading to show a price here.
Although it possible to submit this Market order during liquidity auction, I feel that not showing a price, or showing an explanation of what is happening would be better.

**Comment by MadalinaRaicu** [comment]
we can easily hide it for now. 
what about when the market is in `Monitoring auction - price` mode?

**Comment by PeteWilliams** [comment]
@campbellssource Would it make sense to still show it but add an 'estimated uncrossing price' label, and perhaps a tooltip explaining what that means.

@MadalinaRaicu I think this would apply to both liquidity and price monitoring auctions.

**Comment by MadalinaRaicu** [comment]
does this still apply for Batch auction?

**Comment by MadalinaRaicu** [comment]
Isn't it true that only `Only GTT, GTC and GFA are permitted when the market is in auction` so basically no Market orders (IOC or FOK) are allowed?

**Comment by MadalinaRaicu** [comment]
This order would be rejected: Rejection Reason: "IOC/FOK during auction". This is why I want to revisit order validation. 
https://github.com/vegaprotocol/frontend-monorepo/issues/997

![Screenshot 2022-08-15 at 12 38 59](https://user-images.githubusercontent.com/16125548/184628589-0580e44b-48c0-4370-ab31-c9e4a35d3562.png)

**Comment by PeteWilliams** [comment]
Talked to Michael. In summary…

- Current warning isn't true - you can do some limit orders as well as liquidity provision.
- Give more granular detail of auction type rather than 'suspended'
- Should warn you that you can't make a market order, but not prevent you from submitting one.
- Should be clear that the price for a market order is the indicative uncrossing price

I'd suggest:

**Market order selected:**

_'This market is in auction until it reaches [sufficient liquidity](). You cannot place a market order until the auction ends.'_

_'This market is in auction due to [high price volatility](). You cannot place a market order until the auction ends.'_

**Limit order selected - and TIF != GFA, GTT, GTC**

_'This market is in auction until it reaches [sufficient liquidity](). You can only place Good for Auction, Good till Time, or Good till Cancelled limit orders until the auction ends.'_

_'This market is in auction due to [high price volatility](). You can only place Good for Auction, Good till Time, or Good till Cancelled limit orders until the auction ends.'_

For example:
![image](https://user-images.githubusercontent.com/1325606/185105668-2ad69194-bf9c-4c25-aee8-3e0ad9d0ac81.png)
